### ISSUE TITLE
Week 9 & 10 Project Assignment Feedback

### ISSUE THREAD

**Issue by emily1129** [CryptoEpsilon/SecretSheath#3]
1. Recommend having your file and class name be the same (`add_sharer_to_key.rb`); otherwise it could be bothering in the future
https://github.com/CryptoEpsilon/SecretSheath/blob/61a4247cad11e0bcf00ff6b3f64cd7f8f63a5848/app/services/create_sharer_to_key.rb#L5
2. If you want to list your keys in a folder, shouldn't your route be `[folder_id]/keys]`?
https://github.com/CryptoEpsilon/SecretSheath/blob/61a4247cad11e0bcf00ff6b3f64cd7f8f63a5848/app/controllers/app.rb#L70-L116

**Comment by supakarn-j** [comment]
Thank you TA for the suggestion! all of the issues above has been resolved in `week13`

**Comment by emily1129** [comment]
Thanks for letting me know 😄
